name: start
on:
#for test
  issue_comment:
    types: [created]
#  schedule:
#    - cron:  '0 */8 * * *'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install vpnc, ansible and depends
      run: |
        (sudo apt-get update && sudo apt-get install -y vpnc python3-setuptools p7zip-full unzip)
        (sudo apt-get remove ansible && sudo apt-get install -y openssh-client build-essential libffi-dev libxslt-dev libssl-dev python3 python3-pip git)
        (sudo pip3 install ansible junos-eznc jxmlease ncclient&&ansible-galaxy install Juniper.junos)
    - name: configure ansible
      run: (echo -e "${{ secrets.FULL_HOSTS }}" >> /tmp/inventory&&sudo cp ansible/junos/baseconf/ansible.cfg /tmp/&&sudo cp ansible/junos/tasks/bkp.yml /tmp/)
    - name: connect to vpn
      run: (echo -e "${{ secrets.FULL_CONF }}" >> /tmp/1.conf&&sudo /usr/sbin/vpnc /tmp/1.conf)
    - name: run ansible
      run: (cd /tmp/&&sudo pip3 install ncclient&& ansible-playbook bkp.yml --inventory-file=inventory 2>&1||true)  
    - name: write to git  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         (sudo ls -al /tmp/backups &&sudo date >> /tmp/backups/tmp &&sudo cp /tmp/backups/tmp results/ )
         sudo git config --local user.email "${GITHUB_ACTOR}@gmail.com"
         sudo git config --local user.name "${GITHUB_ACTOR}"
         sudo git remote -v
         sudo git add results/
         sudo git commit -m "clean targets to rep"
         sudo git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main --force 
